### ISSUE TITLE
Check errors with fixed pattern COMET output

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/comet_tools#10]
We use `check_match` in `GbtxMemAnalyzer.py` to check if parsed elinks generated by fixed pattern COMET output contain errors.

The input and output of `check_match` are listed in the `__doc__`.

**Comment by yipengsun** [comment]
First, I don't think it is necessary to use `numpy` in our case. Also, if you really need `numpy`, you need to import it at the beginning of the file:
```python
import numpy as np
```

**Comment by bflaggs** [comment]
The way I wrote the code using numpy is necessary because I wanted to use numpy arrays to check the matching. There probably was a more efficient method for checking the matching although using numpy arrays was the first thing I could think of. I forgot to import numpy when I copied over my code (whoops) but I will do that ASAP.

**Comment by bflaggs** [comment]
I imported `numpy` into the `GbtxMemAnalyzer.py` file on branch ben.

**Comment by yipengsun** [comment]
OK so now at least the code should run. Still, I'm not convinced `numpy` is needed. I think something like this would do:
```python
# Note that ref_data and parsed_data are input parameters of the function

# We loop through the parsed_data
for i in range(0, len(parsed_data)):
    # Note that here each entry is a dictionary, because parsed_data is a list of dictionaries
    d = parsed_data[i]
    ref_d = ref_data[i]
    
    # Then all we need to do is to see if the values agree.
    for elink in ref_d.keys():
	if d[elink] == ref_d[elink]:
	    # this is good
	else:
	    # this is bad
```

**Comment by yipengsun** [comment]
In your code, you used `numpy` to convert a list of dictionary to a 2-dimensional matrix. Once you know the trick about looping through the keys, I don't think converting to matrix is needed.
